"""add_meetup_image_url

Revision ID: 9ae6f7ad0268
Revises: 47c8c746438b
Create Date: 2026-07-01 12:17:34.335842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae6f7ad0268'
down_revision: Union[str, Sequence[str], None] = '47c8c746438b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetups', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetups', 'image_url')
    # ### end Alembic commands ###
