"""add event_date to meetups

Revision ID: e24a1c552d7e
Revises: 875938661870
Create Date: 2026-06-24 11:28:45.680118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24a1c552d7e'
down_revision: Union[str, Sequence[str], None] = '875938661870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetups', sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetups', 'event_date')
    # ### end Alembic commands ###
